# Generated by Django 4.1.3 on 2022-11-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
